### PR TITLE
Monitor chain swap addresses

### LINKED ISSUE #324: Add PENDING_REFUND state
Add a state for when a swap fails and was either automatically triggered for a refund or manually initiated by the user.

### PR DESCRIPTION
**Pull request by dangeross**
This PR adds monitoring of the lockup addresses of incoming chain swaps, to check the state of any unspent funds for the swap lockup address after the swap is finished. It will periodically:
- For every swap with a pending refund tx, check if the lockup address has any unspent outputs. If there are non, sets the swap to Failed/Complete.
- For every swap that is expired, check if the lockup address has any confirmed unspent outputs for a month (4320 blocks). If there are some, sets the swap to Refundable.

In addition the `prepare_refund` / `refund` interface is updated to allow multiple refunds of a swap (after swap the locktime).

The RefundPending state is added to help differentiate between a pending succeeding swap and a failed swap being refunded.

Fixes #324

### CODE REVIEW

File: lib/core/src/chain/bitcoin.rs [hunk 1]
```diff
@@ -101,16 +120,20 @@ impl BitcoinChainService for ElectrumClient {
...
             .into_iter()
             .map(|e| e.into_iter().map(Into::into).collect())
             .collect())
     }
+
+    fn script_list_unspent(&self, script: &Script) -> Result<Vec<Unspent>> {
+        Ok(self
+            .client
+            .script_list_unspent(script)?
+            .into_iter()
```
Comment (ok300) [inline lib/core/src/chain/bitcoin.rs:135]:
```suggestion
            .into_iter()
            .filter(|utxo| script.dust_value().lt(&bitcoin::amount::Amount::from_sat(utxo.value)))
```

Outputs below the dust limit should be ignored when deciding if a swap is refundable or not.

Comment (roeierez) [reply lib/core/src/chain/bitcoin.rs:135]: Not sure about this @ok300. Also there can be several utxos which their aggregated amount is above dust.

Comment (ok300) [reply lib/core/src/chain/bitcoin.rs:135]: Agree. As discussed, we can leave this out.

**Review by ok300 — APPROVED** [review]

File: lib/core/src/sdk.rs [hunk 2]
```diff
@@ -286,22 +289,123 @@ impl LiquidSdk {
...
+                    _ = shutdown_receiver.changed() => {
+                        info!("Received shutdown signal, exiting chain swap transactions loop");
+                        return;
+                    }
+                }
+            }
+        });
+    }
+
+    async fn check_chain_swap_refund_transactions(&self) -> Result<()> {
```
Comment (roeierez) [inline lib/core/src/sdk.rs:334]: I wonder whether we really need this function/tracking.
If the goal is to set the final state of the receive chain swap (Failed/Complete) then I have the following in my mind:
1. The Complete status is set after our claim (liquid) is confirmed and the place we do for lightning swaps is here: https://github.com/breez/breez-liquid-sdk/blob/main/lib/core/src/sdk.rs#L1193 perhaps it is also the place to verify the claim for chain swaps?
2. The Failed status indeed needs to be set when the refund tx is confirmed so perhaps we can wire it to the `check_expired_chain_swap_lockup_transactions` that already checks the expired swaps? maybe set to Failed if unspent_sat=0?

**Comment by dangeross** [comment]
Waiting on #310 to merge

**Review by roeierez — CHANGES_REQUESTED** [review]

File: lib/core/src/sdk.rs (hunk 2 above)
Comment (dangeross) [reply lib/core/src/sdk.rs:334]: There are two functions for the tracking in `check_chain_swap_refund_transactions()`:
1. In the case of a refund during the swap, mark the swap Failed once the lockup is spent. This can be cooperative refunds also, not just expired/non-cooperative. This is only for incoming chain swaps as the outgoing refund is [tracked here](https://github.com/breez/breez-liquid-sdk/blob/a9d75a06727599f813c4dd029150feb3ee03c966/lib/core/src/sdk.rs#L1325-L1331).
2. In the case extra funds sent to the lookup address (outside of the swap flow) and refunds are manually triggered (set back to Pending), mark successful/unsuccessful swap back to Complete/Failed once the funds are spent.

> 1. The Complete status is set after our claim (liquid) is confirmed and the place we do for lightning swaps is here: https://github.com/breez/breez-liquid-sdk/blob/main/lib/core/src/sdk.rs#L1193 perhaps it is also the place to verify the claim for chain swaps?

We could instead move the confirmation (set to Complete) of the incoming chain swap liquid claim here. We also don't monitor the confirmation of the outgoing chain swap bitcoin claim. Maybe we should?

> 2. The Failed status indeed needs to be set when the refund tx is confirmed so perhaps we can wire it to the `check_expired_chain_swap_lockup_transactions` that already checks the expired swaps? maybe set to Failed if unspent_sat=0?

We can but in this case it would only be the non-cooperative / expired refunds.

I main reason for the separation into two functions is to make sure refunds are always handled if the refund is pending.

File: lib/core/src/chain_swap.rs [hunk 3]
```diff
@@ -62,6 +90,87 @@ impl ChainSwapStateHandler {
...
+            .sum())
+    }
+
+    async fn rescan_chain_swap(&self, swap: &ChainSwap, current_height: u32) -> Result<()> {
+        let monitoring_block_height =
+            swap.timeout_block_height + CHAIN_SWAP_MONTIORING_PERIOD_BITCOIN_BLOCKS;
+        let is_swap_expired = current_height > swap.timeout_block_height;
+        let is_monitoring_expired = current_height > monitoring_block_height;
+
+        match swap.state {
```
Comment (roeierez) [inline lib/core/src/chain_swap.rs:137]: Just as an attempt to simplify the match statement here.
Can we replace the match with an if of one condition that checks if the swap  is: 
`!is_monitoring_expired && expired || swap.state == Refundable`

If the given condition is true then update the new state (only if defer from the current state) according to the confirmed unspent amount.
positive => Refundable
zero => if claim then Complete else Failed

File: lib/core/src/chain_swap.rs [hunk 4]
```diff
@@ -62,6 +90,87 @@ impl ChainSwapStateHandler {
         }
     }
 
+    pub(crate) async fn rescan_chain_swaps(&self) -> Result<()> {
```
Comment (roeierez) [inline lib/core/src/chain_swap.rs:93]: NIT: `rescan_incoming_chain_swaps` ?

File: lib/core/src/chain_swap.rs [hunk 5]
```diff
@@ -62,6 +90,87 @@ impl ChainSwapStateHandler {
...
+            .lock()
+            .await
+            .script_list_unspent(script_pubkey.as_script())?
+            .iter()
+            .filter(|u| u.height > 0)
+            .map(|u| u.value)
+            .sum())
+    }
+
+    async fn rescan_chain_swap(&self, swap: &ChainSwap, current_height: u32) -> Result<()> {
```
Comment (roeierez) [inline lib/core/src/chain_swap.rs:131]: NIT: `rescan_incoming_chain_swap` ?

**Review by roeierez — CHANGES_REQUESTED** [review]
Looks good. Dropped some NITs.

**Comment by dangeross** [comment]
Apologies, I've included in the PR adding the RefundPending state because it made sense to use it when monitoring the swap

File: lib/core/src/chain_swap.rs [hunk 6]
```diff
@@ -104,46 +106,56 @@ impl ChainSwapStateHandler {
...
+            let confirmed_unspent_sat: u64 = self
+                .bitcoin_chain_service
+                .lock()
+                .await
+                .script_list_unspent(script_pubkey.as_script())?
+                .iter()
+                .filter(|u| u.height > 0)
+                .map(|u| u.value)
+                .sum();
+            if confirmed_unspent_sat > 0 && swap.state != Refundable {
```
Comment (roeierez) [inline lib/core/src/chain_swap.rs:141]: If the swap is in RefundPending state here (and the refund is not confirmed yet) won't this change its state to Refundable ?

Comment (roeierez) [reply lib/core/src/chain_swap.rs]: OK, reading the docs of script_list_unspent it seems it takes into account mempool spends so in fact if the refund is broadcasted (RefundPending state) then we should get zero unspent.
So it seems it will move RefundPending to Failed/Complete ? I think we are not taking into account the mempool spends here.

Comment (dangeross) [reply lib/core/src/chain_swap.rs]: True, fixed

**Review by roeierez — APPROVED** [review]
LGTM
